# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClassContents_Network_MultiPart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ClassContents_Network_MultiPart

pod 'AFNetworking', '~> 3.0'
end
